# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09

Description: Create-Infra-Ex

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref webserver
      KeyName: AWS_EC2_Demo
      ImageId: 'ami-09d56f8956ab235b3' 
      InstanceType: t3.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0