version: 2.1

jobs:
  #create_infra:
  
   #   docker:
    #    - image: amazon/aws-cli
     # steps:
      #  - checkout # check out the code in the project directory
       # - run: 
        #    name: Create Cloudformation Stack
         #   command: |
          #    aws cloudformation deploy \
           #     --template-file template.yml \
            #    --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
             #   --region us-east-1

  # Exercise: Config and Deployment
 # configure_infra: 
  #  docker:
   #   - image: python:3.7-alpine3.11
    #steps:
     # - checkout
      #- add_ssh_keys:
              # You can get this ID in the section where you registered the  SSH Key
       #       fingerprints: ["ef:7b:ad:02:53:11:ba:a0:eb:24:77:56:e0:73:2e:74"]
      #- run:
       #   name: Install Ansible
        #  command: |
         #   apk add --update ansible
            
            
     # - run:
     #     name: Run Playbook and Configure server
      #    command: |
       #     ansible-playbook -i inventory.txt main.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infra
      #- configure_infra
      - smoke_test