version: 2.1

jobs:
  #create_infra:
  
   #   docker:
    #    - image: amazon/aws-cli
     # steps:
      #  - checkout # check out the code in the project directory
       # - run: 
        #    name: Create Cloudformation Stack
         #   command: |
          #    aws cloudformation deploy \
           #     --template-file template.yml \
            #    --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
             #   --region us-east-1

  # Exercise: Config and Deployment
  configure_infra: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["87:57:b1:7a:ef:52:fe:c3:6b:e5:fd:a8:89:d3:6d:2b"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      #- create_infra
      - configure_infra